# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'guesto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for guesto
	
	pod 'Firebase/Core', '~> 5.4.0'
  	pod 'Firebase/Messaging', '~> 5.4.0'
  
#  pod 'RNSVG', :path => '../node_modules/react-native-svg'


#  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

end


